import { FormControls } from "src/app/Models/FormControl/formcontrol";
export class StateWiseSummaryControl {
  stateWiseSummaryArray: FormControls[];
  invoiceSummaryArray: FormControls[];
  constructor() {
    this.stateWiseSummaryArray = [
      {
        name: "customerName",
        label: "Customer",
        placeholder: "Customer Name",
        type: "text",
        value: "",
        generatecontrol: true,
        disable: true,
        Validations: [],
      },
      {
        name: "cGstin",
        label: "Customer GST",
        placeholder: "Customer GST",
        type: "text",
        value: "",
        generatecontrol: true,
        disable: true,
        Validations: [],
      },
      {
        name: "tGstin",
        label: "Transporter GST ",
        placeholder: "Transporter GST ",
        type: "text",
        value: "",
        generatecontrol: true,
        disable: true,
        Validations: [],
      },
      {
        name: "invoiceDate",
        label: "Invoice Date",
        placeholder: "select Invoice Date",
        type: "date",
        value: new Date(),
        generatecontrol: true,
        disable: true,
        Validations: [],
        additionalData: {
          minDate: new Date()
        },
      },
      {
        name: "cState",
        label: "Customer State",
        placeholder: "Customer State",
        type: "text",
        value: "",
        generatecontrol: true,
        disable: true,
        Validations: [],
      },
      {
        name: "tState",
        label: "Transporter State",
        placeholder: "Transporter State",
        type: "text",
        value: "",
        generatecontrol: true,
        disable: true,
        Validations: [],
      },
      {
        name: "dueDate",
        label: "Due Date",
        placeholder: "select Due Date",
        type: "date",
        value: new Date(),
        generatecontrol: true,
        disable: false,
        Validations: [],
        additionalData: {
          minDate: new Date(),
        },
      },
      {
        name: "gstType",
        label: "GST Type",
        placeholder: "GST Type",
        type: "text",
        value: "",
        generatecontrol: true,
        disable: true,
        Validations: [],
      },
      {
        name: "gstRate",
        label: "GST Rate",
        placeholder: "GST Rate",
        type: "text",
        value: "12%",
        generatecontrol: true,
        disable: true,
        Validations: [],
      },      
      {
        name: "generationOffice",
        label: "Generation Office",
        placeholder: "Generation Office",
        type: "text",
        value:localStorage.getItem("Branch"),
        generatecontrol: true,
        disable: true,
        Validations: [],
      },
      {
        name: "submissionOffice",
        label: "Submission Office",
        placeholder: "Submission Office",
        type: "dropdown",
        value: "",
        generatecontrol: true,
        disable: false,
        Validations: [],
        additionalData: {
          showNameAndValue: false
        },
      },
      {
        name: "collectionOffice",
        label: "Collection Office",
        placeholder: "Collection Office",
        type: "dropdown",
        value: "",
        generatecontrol: true,
        disable: false,
        Validations: [],
        additionalData: {
          showNameAndValue: false
        }
      },
      {
        name: "gstExempted",
        label: "GST Exempted",
        placeholder: "",
        type: "toggle",
        value: "",
        generatecontrol: true,
        disable: false,
        functions:{
          onChange:"gstExemptedChange"
        },
        Validations: [],
      },
      {
        name: "ExemptionReason",
        label: "Exemption reason",
        placeholder: "Exemption reason",
        type: "dropdown",
        value: "",
        generatecontrol: true,
        disable: false,
        Validations: [],
        additionalData: {
          showNameAndValue: false
        },
      },
      {
        name: "",
        label: "",
        placeholder: "",
        type: "",
        value: "",
        generatecontrol: true,
        disable: false,
        Validations: [],
      },
      // {
      //   name: "MIN",
      //   label: "Manual Invoice Number",
      //   placeholder: "Manual Invoice Number",
      //   type: "text",
      //   value: "",
      //   generatecontrol: true,
      //   disable: false,
      //   Validations: [],
      // },

      {
        name: "unbilledAmount",
        label: "Unbilled Amount(₹)",
        placeholder: "Unbilled Amount(₹)",
        type: "",
        value: "",
        generatecontrol: false,
        disable: false,
        Validations: [],
      },
      // {
      //   name: "remark",
      //   label: "Remark",
      //   placeholder: "Remark",
      //   type: "text",
      //   value: "",
      //   generatecontrol: true,
      //   disable: false,
      //   Validations: [],
      // },
      // {
      //   name: "referenceNo",
      //   label: "ReferenceNo",
      //   placeholder: "ReferenceNo",
      //   type: "text",
      //   value: "",
      //   generatecontrol: true,
      //   disable: false,
      //   Validations: [],
      // },

      // {
      //   name: "tCity",
      //   label: "Transporter City",
      //   placeholder: "Transporter City",
      //   type: "text",
      //   value: "",
      //   generatecontrol: true,
      //   disable: false,
      //   Validations: [],
      // },

      // {
      //   name: "cCity",
      //   label: "Customer City",
      //   placeholder: "Customer City",
      //   type: "text",
      //   value: "",
      //   generatecontrol: true,
      //   disable: false,
      //   Validations: [],
      // },
      // {
      //   name: "address",
      //   label: "Address",
      //   placeholder: "BillingAddress",
      //   type: "text",
      //   value: "",
      //   generatecontrol: true,
      //   disable: false,
      //   Validations: [],
      // },
      // {
      //   name: "bgl",
      //   label: "Bill Generation Location",
      //   placeholder: "Bill Generation Location",
      //   type: "text",
      //   value: "",
      //   generatecontrol: true,
      //   disable: false,
      //   Validations: [],
      // },
      // {
      //   name: "bsl",
      //   label: "Bill Submission Location",
      //   placeholder: "Bill Submission Location",
      //   type: "text",
      //   value: "",
      //   generatecontrol: true,
      //   disable: false,
      //   Validations: [],
      // },
      // {
      //   name: "bcl",
      //   label: "Bill Collection Location",
      //   placeholder: "Bill Collection Location",
      //   type: "text",
      //   value: "",
      //   generatecontrol: true,
      //   disable: false,
      //   Validations: [],
      // },
      // {
      //   name: "locationFilter",
      //   label: "Location Filter",
      //   placeholder: "Location Filter",
      //   type: "text",
      //   value: "",
      //   generatecontrol: true,
      //   disable: false,
      //   Validations: [],
      // },
      // {
      //   name: "exemptedCategory",
      //   label: "Exempted Category",
      //   placeholder: "Exempted Category",
      //   type: "text",
      //   value: "",
      //   generatecontrol: true,
      //   disable: false,
      //   Validations: [],
      // },
      // {
      //   name: "unregistered",
      //   label: "Unregistered",
      //   placeholder: "",
      //   type: "toggle",
      //   value: "",
      //   generatecontrol: true,
      //   disable: false,
      //   Validations: [],
      // },
      // {
      //   name: "roundoffAmount",
      //   label: "Round off Amount",
      //   placeholder: "",
      //   type: "toggle",
      //   value: "",
      //   generatecontrol: true,
      //   disable: false,
      //   Validations: [],
      // },

      // {
      //   name: "roundoffGSTAmount",
      //   label: "Round off GST Amount",
      //   placeholder: "",
      //   type: "toggle",
      //   value: "",
      //   generatecontrol: true,
      //   disable: false,
      //   Validations: [],
      // },
      {
        name: "invoiceNo",
        label: "",
        placeholder: "",
        type: "",
        value: "",
        Validations: [],
        generatecontrol: false,
        disable: false,
      },
      // {
      //   name: "prqNo",
      //   label: "",
      //   placeholder: "",
      //   type: "",
      //   value: "",
      //   Validations: [],
      //   generatecontrol: false,
      //   disable: false,
      // },
      {
        name: "billingAmount",
        label: "",
        placeholder: "",
        type: "",
        value: "",
        Validations: [],
        generatecontrol: false,
        disable: false,
      },
      {
        name: "pAYBAS",
        label: "",
        placeholder: "",
        type: "",
        value: "P02",
        generatecontrol: false,
        disable: false,
        Validations: [],
      },
      {
        name: "gstCt",
        label: "",
        placeholder: "",
        type: "",
        value: "",
        generatecontrol: false,
        disable: false,
        Validations: [],
      },
      {
        name: "gstSt",
        label: "",
        placeholder: "",
        type: "",
        value: "",
        generatecontrol: false,
        disable: false,
        Validations: [],
      }
      // {
      //   name: "_id",
      //   label: "",
      //   placeholder: "",
      //   type: "",
      //   value: "",
      //   Validations: [],
      //   generatecontrol: false,
      //   disable: false,
      // },
    ];
    this.invoiceSummaryArray = [
      {
        name: "shipmentCount",
        label: "Shipment Count",
        placeholder: "Shipment Count",
        type: "number",
        value: "",
        generatecontrol: true,
        disable: true,
        Validations: [],
      },
      {
        name: "shipmentTotal",
        label: "Shipment Total(₹)",
        placeholder: "Shipment Total(₹)",
        type: "text",
        value: "",
        generatecontrol: true,
        disable: true,
        Validations: [],
      },     
      {
        name: "gst",
        label: "GST(₹)",
        placeholder: "GST(₹)",
        type: "text",
        value: "",
        generatecontrol: true,
        disable: true,
        Validations: [],
      },
      {
        name: "igst",
        label: "IGST(₹)",
        placeholder: "IGST(₹)",
        type: "text",
        value: "",
        generatecontrol: true,
        disable: true,
        Validations: [],
      },      
      {
        name: "cgst",
        label: "CGST(₹)",
        placeholder: "CGST(₹)",
        type: "text",
        value: "",
        generatecontrol: true,
        disable: true,
        Validations: [],
      },      
      {
        name: "sgst",
        label: "SGST(₹)",
        placeholder: "SGST(₹)",
        type: "text",
        value: "",
        generatecontrol: true,
        disable: true,
        Validations: [],
      },
      {
        name: "utgst",
        label: "UTGST(₹)",
        placeholder: "UTGST(₹)",
        type: "text",
        value: "",
        generatecontrol: true,
        disable: true,
        Validations: [],
      },
      {
        name: "invoiceTotal",
        label: "Invoice Total(₹)",
        placeholder: "Invoice Total(₹)",
        type: "number",
        value: "",
        generatecontrol: true,
        disable: true,
        Validations: [],
      },
      {
        name: "roundOff",
        label: "Round off",
        placeholder: "Round off",
        type: "number",
        value: 0,
        generatecontrol: true,
        disable: false,
        functions:{
         onChange:"roundOffChange"
        },
        Validations: [],
      },
      {
        name: "finalInvoice",
        label: "Final Invoice (₹)",
        placeholder: "Final Invoice(₹)",
        type: "number",
        value: "",
        generatecontrol: true,
        disable: true,
        Validations: [],
      },
      {
        name: "supportingDocument",
        label: "Supporting document",
        placeholder: "Select Supporting document",
        type: "file",
        value: "",
        generatecontrol: true,
        disable: false,
        Validations: [],
      },
    ]
  }

  getstateWiseSummaryArrayControls() {
    return this.stateWiseSummaryArray;
  }
  getInvoiceSummaryArrayControls() {
    return this.invoiceSummaryArray;
  }
}
